In [ ]:
import numpy as np


In [ ]:

def cal_heuristic(matrix, Queens):
  pair=[]
  attack_count = 0
  for Queen in Queens:
    ind_i=Queen[0]
    ind_j = Queen[1]
    rowz=5
    
  #  print(ind_i, ind_j)

    for i in range (1, 5):
      if (ind_i -i>=0 and ind_j +i <=4):
        dig1=[ind_i -i, ind_j +i]
        if matrix[dig1[0]][dig1[1]]==1:
          attack_count+=1
          pair.append(sorted([ind_j, ind_j +i]))
          # print('dig side 1:', dig1)

      if (ind_i +i<=4 and ind_j -i >=0): 
        dig2=[ind_i +i, ind_j - i]
        if matrix[dig2[0]][dig2[1]]==1:
          attack_count+=1
          pair.append(sorted([ind_j, ind_j - i]))
#          print('dig side 2:',ind_j, ind_j - i)
      
      if (ind_i-i >=0 and ind_j-i>=0):
        dig3=[ind_i-i, ind_j-i]
        if matrix[dig3[0]][dig3[1]]==1:
          attack_count+=1
          pair.append(sorted([ind_j, ind_j-i]))
#          print('dig side 3:',dig3)

      if (ind_i+i <=4 and ind_j+i<=4):
        dig4=[ind_i+i, ind_j+i]
        if matrix[dig4[0]][dig4[1]]==1:
          attack_count+=1
          pair.append(sorted([ind_j, ind_j+i]))
    #      print('dig side 4:',dig4)

      if(ind_j+i<=4):
        row_wise1= [ind_i, ind_j+i]
        if matrix[row_wise1[0]][row_wise1[1]]==1:
          attack_count+=1
          pair.append(sorted([ind_j, row_wise1[1]]))
  #        print('row fw',row_wise1)
      if(ind_j-i>=0):
        row_wise2= [ind_i, ind_j-i]
        if matrix[row_wise2[0]][row_wise2[1]]==1:
          attack_count+=1
#          print(sorted([ind_j, row_wise2[1]]))
          pair.append(sorted([ind_j, row_wise2[1]]))
    #      print('row bw',row_wise2)

  y= np.array(pair) 

  unique_data = [list(x) for x in set(tuple(x) for x in y)]
  attack_count=(len(unique_data))
 # print(unique_data)
  return attack_count


In [ ]:
matrix= np.zeros((5,5), dtype=int)
matrix[0][0]=1
matrix[1][1]=1
matrix[1][2]=1
matrix[3][3]=1
matrix[3][4]=1
print(matrix)

# matrix= np.zeros((5,5), dtype=int)
# matrix[2][0]=1
# matrix[4][1]=1
# matrix[1][2]=1
# matrix[3][3]=1
# matrix[3][4]=1
# print(matrix)

Goal=matrix.copy()
Queens=np.transpose(np.nonzero(matrix))
cal_heuristic(matrix, Queens)

[[1 0 0 0 0]
 [0 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]
 [0 0 0 0 0]]


6

In [ ]:

def EightQueen(matrix):
  Goal=matrix.copy()
  Queen=np.transpose(np.nonzero(matrix))

  best_heuristic = cal_heuristic(matrix, Queens)
  print('Initial Heuristic', best_heuristic)
  count=0

  for Q in range(5):
    Queen=np.transpose(np.nonzero(matrix))
    heuristic = cal_heuristic(matrix, Queen)
    #print(Queen)
    i = Queen[Q][0]
    j= Queen[Q][1]
    # matrix[]
    # print(i)
    
    for col in range(5):
  #   print(col)
      
      new_matrix= matrix.copy()
      new_matrix[i][j]=0
      if col != i:
        count+=1
        new_matrix[col][j]=1
        Queen_new=np.transpose(np.nonzero(new_matrix))
        heuristic1 = cal_heuristic(new_matrix, Queen_new)
        if heuristic1 < best_heuristic: 
 #           print('Compare ',best_heuristic, heuristic1)
          best_heuristic=heuristic1
          best_matrix= new_matrix
      # print(new_matrix)
        #print('h value',heuristic1)
    new_matrix= matrix.copy()
  print('Final Heuristic Value :, ', best_heuristic)
  if best_heuristic == 0:
    print('The Goal Matrix is : ')
#    print(best_matrix)
    return (best_matrix)
  else:
    EightQueen(best_matrix)

EightQueen(matrix)

  #print(heuristic)

Initial Heuristic 6
Final Heuristic Value :,  3
Initial Heuristic 6
Final Heuristic Value :,  2
Initial Heuristic 6
Final Heuristic Value :,  0
The Goal Matrix is : 
